-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


ALTER TABLE IF EXISTS public.idea DROP CONSTRAINT IF EXISTS creator;

ALTER TABLE IF EXISTS public.idea DROP CONSTRAINT IF EXISTS posts;

ALTER TABLE IF EXISTS public.upvote DROP CONSTRAINT IF EXISTS None;

ALTER TABLE IF EXISTS public.upvote DROP CONSTRAINT IF EXISTS None;

ALTER TABLE IF EXISTS public.post DROP CONSTRAINT IF EXISTS None;

ALTER TABLE IF EXISTS public.image DROP CONSTRAINT IF EXISTS None;

ALTER TABLE IF EXISTS public.comment DROP CONSTRAINT IF EXISTS None;

ALTER TABLE IF EXISTS public.comment DROP CONSTRAINT IF EXISTS None;



DROP TABLE IF EXISTS public."user";

CREATE TABLE IF NOT EXISTS public."user"
(
    id serial NOT NULL,
    name character varying(32) NOT NULL,
    email character varying(512) NOT NULL,
    password character varying(32) NOT NULL,
    PRIMARY KEY (id),
    UNIQUE (name)
);

DROP TABLE IF EXISTS public.idea;

CREATE TABLE IF NOT EXISTS public.idea
(
    id serial NOT NULL,
    user_id integer NOT NULL,
    title character varying(512) NOT NULL,
    post_id integer NOT NULL,
    PRIMARY KEY (id, user_id),
    UNIQUE (id),
    CONSTRAINT header UNIQUE (post_id)
);

DROP TABLE IF EXISTS public.upvote;

CREATE TABLE IF NOT EXISTS public.upvote
(
    user_id integer NOT NULL,
    post_id integer NOT NULL,
    upvote_date date NOT NULL,
    PRIMARY KEY (user_id, post_id)
);

DROP TABLE IF EXISTS public.post;

CREATE TABLE IF NOT EXISTS public.post
(
    idea_id integer NOT NULL,
    id serial NOT NULL,
    text character varying(4000),
    creation_date date NOT NULL,
    PRIMARY KEY (idea_id, id),
    UNIQUE (id)
);

DROP TABLE IF EXISTS public.image;

CREATE TABLE IF NOT EXISTS public.image
(
    url character varying(256) NOT NULL,
    post_id integer NOT NULL,
    PRIMARY KEY (url, post_id)
);

DROP TABLE IF EXISTS public.comment;

CREATE TABLE IF NOT EXISTS public.comment
(
    id serial NOT NULL,
    user_id integer NOT NULL,
    post_id integer NOT NULL,
    text character varying(4000) NOT NULL,
    PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS public.idea
    ADD CONSTRAINT creator FOREIGN KEY (user_id)
    REFERENCES public."user" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.idea
    ADD CONSTRAINT posts FOREIGN KEY (post_id)
    REFERENCES public.post (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.upvote
    ADD FOREIGN KEY (user_id)
    REFERENCES public."user" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.upvote
    ADD FOREIGN KEY (post_id)
    REFERENCES public.post (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.post
    ADD FOREIGN KEY (idea_id)
    REFERENCES public.idea (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.image
    ADD FOREIGN KEY (post_id)
    REFERENCES public.post (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.comment
    ADD FOREIGN KEY (user_id)
    REFERENCES public."user" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.comment
    ADD FOREIGN KEY (post_id)
    REFERENCES public.post (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;